Install nginx on remote server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -3,22 +3,33 @@
 # Making assumptions that if ngix is installed,
 # Then it is already configured per the requirements
 
-function install_and_configure_nginx(){
-    sudo apt update && sudo apt install --yes nginx;
-    sudo chown -R "$USER":"$USER" /var/www/
-    echo "Hello World!" > /var/www/html/index.html
-    mkdir -p /var/www/mysite
-    cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
-    echo "Hello World!" > /var/www/html/index.nginx-debian.html
-    echo "Hello World!" > /var/www/mysite/index.html
-    sudo chown -R "$USER":"$USER" /etc/nginx/conf.d
-    echo -e "server {\n \tlisten\t80;\n \troot \t/var/www/mysite; \n\tlocation / {\n  \t\troot\t/var/www/mysite;\n\t}\n}\t" > /etc/nginx/conf.d/mysite.conf
-
-    sudo nginx -s reload
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
 }
-
-if [[ $(which nginx) ]]; then
-    echo "You have Nginx installed already. I assume it's configured too";
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
 else
-install_and_configure_nginx;
+    echo "Could not install nginx"
+    exit 1
 fi
+exit 0
